name: Deploy to the production env

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-self-contained.yml
    with:
      environment_label: production
      deploy_path: /var/www/HappyNotes.Api
      port: "5012"
      service_name: HappyNotes.Api.service
      host_token: happynotes-api
    secrets:
      MYSQL_PASSWORD: ${{ secrets.PRODUCTION_MYSQL_PASSWORD }}
      SYMMETRIC_SECURITY_KEY: ${{ secrets.PRODUCTION_SYMMETRIC_SECURITY_KEY }}
      SEQ_API_KEY: ${{ secrets.PRODUCTION_SEQ_API_KEY }}
