name: Deploy to production test env (EXPERIMENTAL)

# Manual trigger only for safety
on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-self-contained.yml
    with:
      environment_label: production-test
      deploy_path: /var/www/HappyNotes.Api.test
      port: "5013"
      service_name: HappyNotes.Api.test.service
      host_token: happynotes-api-test
    secrets:
      MYSQL_PASSWORD: ${{ secrets.PRODUCTION_MYSQL_PASSWORD }}
      SYMMETRIC_SECURITY_KEY: ${{ secrets.PRODUCTION_SYMMETRIC_SECURITY_KEY }}
      SEQ_API_KEY: ${{ secrets.PRODUCTION_SEQ_API_KEY }}
